test:
  adapter: postgresql
  database: kaminari_test
  username: postgres

development:
  adapter: postgresql
  database: kaminari_dev
  username: postgres

production:
  adapter: postgresql
  database: kaminari_pro
  username: postgres
